
services:
  db:
    image: mysql:8.0
    container_name: mail-svc-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASS}
      MYSQL_DATABASE: mailsvc_db
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: ${DB_USER_PASS}
    ports:
      - "3306:3306"
    networks:
      - appnet


  application:
    image: mihaylov79/mail-svc:latest
    container_name: mail-svc-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mailsvc_db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: ${DB_USER_PASS}
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - appnet

networks:
  appnet:
