name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package

    - name: Build image
      run: docker build -t mihaylov79/mail-svc:latest .

    - name: Docker login
      run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

    - name: Push image to Dockerhub
      run: docker push mihaylov79/mail-svc:latest
      
