name: 'mail-svc-Terraform Deployment'

on:
  workflow_dispatch:

jobs:
  init-validate-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

      - name: Set Azure subscription
        run: az account set --subscription ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan \
            -var="subscription_id=942b7e66-7845-4024-b5b2-195cf7591ab6" \
            -var="tenant_id=4a06d40c-e447-42be-baef-dd0421ed10bd"
        env:
          TF_VAR_mailsvc_db_root_pass: ${{ secrets.DB_ROOT_PASS }}
          TF_VAR_mailsvc_db_user_pass: ${{ secrets.DB_USER_PASS }}

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: deploy/tfplan

  apply:
    runs-on: ubuntu-latest
    needs: init-validate-plan
    defaults:
      run:
        working-directory: ./deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

      - name: Set Azure subscription
        run: az account set --subscription ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: deploy

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_mailsvc_db_root_pass: ${{ secrets.DB_ROOT_PASS }}
          TF_VAR_mailsvc_db_user_pass: ${{ secrets.DB_USER_PASS }}
