name: 'mail-svc-Terraform Deployment'

on:
 # workflow_run:
 #   workflows: ["Build and Test"]
 #   types:
 #     - completed
 workflow_dispatch:

jobs:
  init-validate-plan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Validare
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

      env:
        TF_VAR_mailsvc_db_root_pass: ${{secrets.DB_ROOT_PASS}}
        TF_VAR_mailsvc_db_user_pass: ${{secrets.DB_USER_PASS}}
        TF_VAR_subscription_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        TF_VAR_tenant_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

   # TODO : Трябва да се допише Аpply-a 
